In [1]:
from alyx_connector import Connector
connector = Connector()

# List the available endpoints

In [2]:
connector.web_client.list_endpoints()

['/api/auth-token',
 '/api/brain-regions',
 '/api/brain-regions/{id}',
 '/api/cache.zip',
 '/api/cache/info/',
 '/api/channels',
 '/api/channels/{id}',
 '/api/data-formats',
 '/api/data-formats/{name}',
 '/api/data-repository',
 '/api/data-repository-type',
 '/api/data-repository-type/{name}',
 '/api/data-repository/{name}',
 '/api/dataset-types',
 '/api/dataset-types/{name}',
 '/api/datasets',
 '/api/datasets/{id}',
 '/api/downloads',
 '/api/downloads/{id}',
 '/api/files',
 '/api/files/{id}',
 '/api/insertions',
 '/api/insertions/{id}',
 '/api/labs',
 '/api/labs/{name}',
 '/api/locations',
 '/api/locations/{name}',
 '/api/media/{img_url}',
 '/api/new-download',
 '/api/notes',
 '/api/notes/{id}',
 '/api/procedures',
 '/api/projects',
 '/api/projects/{name}',
 '/api/register-file',
 '/api/revisions',
 '/api/revisions/{name}',
 '/api/server-info',
 '/api/sessions',
 '/api/sessions/{id}',
 '/api/sessions/{name}',
 '/api/subjects',
 '/api/subjects/{name}',
 '/api/surgeries',
 '/api/sync-file-status',
 '/api/tags',
 '/api/tags/{id}',
 '/api/tasks',
 '/api/tasks/{id}',
 '/api/trajectories',
 '/api/trajectories/{id}',
 '/api/users',
 '/api/users/{username}',
 '/api/water-administrations',
 '/api/water-administrations/{id}',
 '/api/water-requirement/{name}',
 '/api/water-restricted-subjects',
 '/api/water-restriction',
 '/api/water-type',
 '/api/water-type/{name}',
 '/api/weighings',
 '/api/weighings/{id}']

# Use one endpoint to create an object
(taking as an example a mouse)

In [13]:
labs = connector.web_client.rest("labs", "list")
labs

,institution,address,timezone,repositories,reference_weight_pct,zscore_weight_pct,json
name,,,,,,,
HaissLab,Pasteur,25 rue du Dr. Roux,GB,[],0.83,0.06,None
defaultlab,,,Europe/Paris,[],0.00,0.00,None

In [19]:
lab = connector.web_client.rest("labs", "create", data={"name":"TestingGrounds"})
lab

institution
address
timezone                Europe/Paris
repositories                      []
reference_weight_pct             0.0
zscore_weight_pct                0.0
json                            None
Name: TestingGrounds, dtype: object

In [20]:
value = connector.web_client.rest("subjects", "create", data={"nickname":"mickey_17", "lab":"TestingGrounds"})
value

nickname                                                          mickey_17
url                       http://127.0.0.1/api/subjects/TestingGrounds__...
id                                     ac57d3e5-2977-4380-b139-8450cc0875d3
responsible_user                                                   tjostmou
birth_date                                                             None
age_weeks                                                                 0
death_date                                                             None
species                                                        Mus musculus
sex                                                                       U
litter                                                                 None
strain                                                                 None
source                                                                 None
line                                                                   None
projects                                                                 []
session_projects                                                         []
lab                                                          TestingGrounds
genotype                                                                 []
description
alive                                                                  True
reference_weight                                                        0.0
last_water_restriction                                                 None
expected_water                                                          0.5
remaining_water                                                         0.5
Name: TestingGrounds__mickey_17, dtype: object

In [21]:
subjects = connector.web_client.rest("subjects", "list", lab="TestingGrounds")
subjects

,id,nickname,url,responsible_user,birth_date,age_weeks,death_date,species,sex,litter,...,projects,session_projects,lab,genotype,description,alive,reference_weight,last_water_restriction,expected_water,remaining_water
name,,,,,,,,,,,,,,,,,,,,,
TestingGrounds__mickey_17,ac57d3e5-2977-4380-b139-8450cc0875d3,mickey_17,http://127.0.0.1/api/subjects/TestingGrounds__...,tjostmou,None,0,None,Mus musculus,U,None,...,[],[],TestingGrounds,[],,True,0.0,None,0.5,0.5

In [24]:
# A subject's name (unique) is created from lab_name__subject_nickname
# Users can still search by nickname if they want
value = connector.web_client.rest("subjects", "list", nickname="mickey_17")
value

,id,nickname,url,responsible_user,birth_date,age_weeks,death_date,species,sex,litter,...,projects,session_projects,lab,genotype,description,alive,reference_weight,last_water_restriction,expected_water,remaining_water
name,,,,,,,,,,,,,,,,,,,,,
TestingGrounds__mickey_17,ac57d3e5-2977-4380-b139-8450cc0875d3,mickey_17,http://127.0.0.1/api/subjects/TestingGrounds__...,tjostmou,None,0,None,Mus musculus,U,None,...,[],[],TestingGrounds,[],,True,0.0,None,0.5,0.5

In [ ]:
# A subject's name (unique) is created from lab_name__subject_nickname
# Users can still search by nickname if they want
value = connector.web_client.rest("subjects", "destroy", name="TestingGrounds__mickey_17")

In [12]:
value = connector.web_client.rest("labs", "destroy", name="TestingGrounds")